name: Run all tests

on: 
	[push, pull_request]
jobs:
	run-my_tests:
		runs-on: ubuntu-latest
		
	steps:
		-uses: actions/checkout@v2
		-name: set up python
		uses: actions/setup-python@v2
		with:
			python-version: 3.9
		-name: install dependencies
		run:
			python -m pip install pytest numpy
		-name: finally my tests
		run:
			pytest -sv test_logistic.py
